name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests: # Имя
    runs-on: [ubuntu-latest] # Контейнер
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      run:  echo ${{ secrets.DOCKER_PWD }} | echo ${{ secrets.DOCKER_LOGIN }}