name: Secrets

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    # Первую джобу смело можем копипастить из экшена для тестирования
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      env:
        LOGIN: ${{ secrets.DOCKER_LOGIN }}
        NAME: ${{ secrets.DOCKER_NAME }}
      - name: Test
        run: echo $LOGIN | echo $NAME