name: Secrets

on:
  release:
    types: [published]
  # Запуск только при публиковании нового релиза

jobs:
  run_tests:
    # Первую джобу смело можем копипастить из экшена для тестирования
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - name: Test
      - run: echo ${{ secrets.DOCKER_LOGIN }} | echo ${{ secrets.DOCKER_PWD }}