name: Secrets

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    # Первую джобу смело можем копипастить из экшена для тестирования
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - name: Test
        env:
            LOGIN: ${{ secrets.DOCKER_LOGIN }}
            NAME: ${{ secrets.DOCKER_NAME }}
        run: echo $LOGIN | echo $NAME | echo "smth"
        